name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: chmod 777 ./gradlew && ./gradlew :app:assembleRelease && find app/build/outputs
    - name: Android Sign
      # You may pin to the exact commit or the version.
      # uses: Tlaster/android-sign@1c5bf4b2fa309acb0c0ae0bf9379ab458f14d5b1
      uses: Tlaster/android-sign@v1.2.2
      with:
        # The directory to find your release to sign
        releaseDirectory: app/build/outputs/apk/common/release/
        # The key used to sign your release in base64 encoded format
        signingKeyBase64: ${{ secrets.SIGNING_KEY }} 
        # The key alias
        alias: ${{ secrets.ALIAS }}
        # The password to the keystore
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        # The password for the key
        keyPassword: ${{ secrets.KEY_PASSWORD }}# optional
        # The working directory for action, default to build
        #buildDirectory: # optional
        # The output directory for sign, default to build/signed
        #output: # optional
    

    - name: Upload apk
      uses: actions/upload-artifact@v1
      with:
        name: app-armeabi-v7a-release-unsigned.apk
        path: app/build/outputs/apk/common/release/app-common-armeabi-v7a-release-unsigned.apk

